### ISSUE TITLE
new Update Multiplayer

### ISSUE THREAD

**Issue by Gordon1fm** [Craxy/Parkitect-HideScenery#3]
with new AbstractMod Framework.

Please fix this Mod. ^^

**Comment by Craxy** [comment]
Updated here on GitHub and on Steam

I didn't test the mod in multiplayer with others (only alone on a custom server) -- but should work.
Mod isn't required by all players. And I think transparency is only shown locally and not for all players.

(I hope it works with: one player hides some scenery, other player deletes some of that hidden scenery. In local play that doesn't cause any issues with the exception of still counting the deleted, hidden objects in the side bar. But that doesn't cause any real errors and counter resets on "Clear")
